// Demo data fallback when Supabase is not configured
import { Post } from '@/lib/types/database'

const demoPost: Post = {
  id: 'demo-1',
  title: 'Getting Started with RapidReach',
  slug: 'getting-started',
  excerpt: 'Welcome to RapidReach! This is a demo post. Connect your Supabase database to see real content.',
  content: '# Welcome\n\nThis is demo content. Please configure your Supabase connection.',
  author_id: 'demo-author',
  author: {
    id: 'demo-author',
    email: 'demo@rapidreach.blog',
    full_name: 'Demo Author',
    username: 'demo',
    role: 'admin',
    is_active: true,
    is_verified: true,
    email_notifications: true,
    comment_notifications: true,
    newsletter_subscribed: false,
    posts_written: 1,
    comments_posted: 0,
    total_views_received: 0,
    total_likes_received: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  category: 'Platform Engineering',
  tags: ['demo', 'setup', 'getting-started'],
  difficulty: 'beginner',
  status: 'published',
  featured: true,
  trending: false,
  view_count: 0,
  unique_view_count: 0,
  like_count: 0,
  comment_count: 0,
  share_count: 0,
  bookmark_count: 0,
  read_time: 5,
  word_count: 100,
  character_count: 500,
  published_at: new Date().toISOString(),
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const demoPosts: Post[] = [
  demoPost,
  {
    ...demoPost,
    id: 'demo-2',
    title: 'Configure Your Supabase Connection',
    slug: 'configure-supabase',
    excerpt: 'Follow the SETUP_GUIDE.md to connect your Supabase database and enable all features.',
    featured: false,
    trending: true,
  },
  {
    ...demoPost,
    id: 'demo-3',
    title: 'Explore Admin Features',
    slug: 'admin-features',
    excerpt: 'Once connected, explore post management, user administration, and analytics.',
    featured: false,
    trending: false,
  },
]
